// This file was autogenerated by calcdeps.py
goog.addDependency("../../../js/script.js", [], ['profile.UserNameEdit', 'profile.EmailEdit']);
goog.addDependency("../../../js/jquery-2.2.3.min.js", [], []);
goog.addDependency("../../../js/jq_script.js", [], []);
goog.addDependency("../../../js/my-deps.js", [], []);
goog.addDependency("../../../js/profile/EmailEdit.js", ['profile.EmailEdit'], ['goog.dom.classes', 'goog.dom.classlist', 'goog.events', 'goog.soy', 'goog.ui.Component']);
goog.addDependency("../../../js/profile/UserNameEdit.js", ['profile.UserNameEdit'], ['goog.dom.classes', 'goog.dom.classlist', 'goog.events', 'goog.soy', 'goog.ui.Component']);
